// <auto-generated />
namespace Garage20.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_parkinglots : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_parkinglots));
        
        string IMigrationMetadata.Id
        {
            get { return "201710250958564_add_parkinglots"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
